### ISSUE TITLE
Add a "Title" field to the ObservationForm (and the view) that is an editable, optional text box

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#18]
"Title. We fought about whether this would be required, and we think NO.  But as we have visualizations (like the star chart), it will be important to have the option for more memorable names… [LOWER PRIORITY]"

This will need to be added to the `Observation` model, the `ObservationForm` form, and to the UI itself.

**Comment by cbradyatinquire** [comment]
The title helps to identify observations when they're in the ANALYSIS and review mode.  For example, when you've gone back and talked about an observation as a teacher group, you want to be able to make it easier to reference in the future.  So a title rather than date and constructs is good to have.
