### ISSUE TITLE
Show context tags as additional toggles on the observation page

### ISSUE THREAD

**Issue by zachmccormick** [TrailblazingTech/LSOA#46]
I think these should also be selectable on the observation page as things you can tag an observation with. Right now if you pick a bunch of tags in the setup screen, they are applied to all of your observations. I think this should be toggle-able just like the learning construct sublevels are. Right now the tags aren't even visible on the screen on the observation page.

**Comment by zachmccormick** [comment]
Right now if you pick a bunch of tags in the setup screen, they are applied to all of your observations hence-forth. I think this should be toggle-able just like the learning construct sublevels are. Right now the tags aren't even visible on the screen...

**Comment by cbradyatinquire** [comment]
@zachmccormick I think I agree with you.  AT LEAST it should be the case that the context tags are VISIBLE on the observation screen.  Maybe they are properties of the OBSERVATION SESSION, but they can be toggled OFF for any particular observation (so, they're like the sublevels, but their selection is the INVERSE - they're by default ON, and toggleable off, rather than the sublevels that are by-default OFF and toggleable to select.).
