### ISSUE TITLE
Observation Screen: Persist both original and annotated image

### ISSUE THREAD

**Issue by cbradyatinquire** [TrailblazingTech/LSOA#95]
The intent is for image annotations (i.e., pen drawings on top of them) to be a part of the observation.  So, they should appear wherever the observation is shown.  On the other hand, they should be separable from the image as a MEDIA entry.  So that when the user creates a second observation on the same image, they should be able to draw on it it differently.

**Comment by zachmccormick** [comment]
This can be solved by saving both the original image and the annotated image to the database/s3. Right now we are saving the annotation as JSON in the database (which means we could technically redraw it) and the original image.

Let's additionally store a second copy of the image, as the "annotated image", then use that image when viewing previous observations or viewing any of the star chart observation modals.

We should continue to use the _original image_ if the user selects "Use Last Observation" from the observation screen (so that they can annotate a fresh image).
